version: "3.1"
services:
    gvm:
        image: gvm
        volumes:
          - gvm-data:/data
        environment:
          - USERNAME="admin"
          - PASSWORD="Ac492bhz3" #Please use 10+ Characters consisting of numbers, lower & upper case  letters
          - HTTPS=true
          - TZ="ETC"
          - SSHD=true
          - DB_PASSWORD="Ac492bhz3"
        ports:
          - "443:9392"  # Web interface
          - "5432:5432" # Access PostgreSQL database from external tools
          - "2222:22"   # SSH for remote sensors
        restart: unless-stopped
volumes:
    gvm-data:
